### ISSUE TITLE
TUFLOW ARR2016 download

### ISSUE THREAD

**Issue by locky123** [TUFLOW-Support/QGIS-TUFLOW-Plugin#10]
Hi, 
I am trying to use the "Extract ARR2016 to TUFLOW" tool. 
I am using QGIS Version 3.2 and TUFLOW QGIS Utility Build: 2018-04-AA
However when I start the process I get the following error in the log.txt file:

python3: can't open file 'C:\Users\Modeller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\ARR2016\ARR_to_TUFLOW.py': [Errno 2] No such file or directory

As the ARR2016 folder does not exist, I copied it from a previous version and got the following error in the log.txt file:

Traceback (most recent call last):
  File "C:\Users\Modeller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\ARR2016\ARR_to_TUFLOW.py", line 5, in <module>
    import ARR_WebRes
  File "C:\Users\Modeller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\ARR2016\ARR_WebRes.py", line 16, in <module>
    from ARR_TUFLOW_func_lib import *
  File "C:\Users\Modeller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\ARR2016\ARR_TUFLOW_func_lib.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\matplotlib\backends\qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'

Has anyone recently come across this or have any ideas?

**Comment by TUFLOW-Support** [comment]
Hi Locky,

There is a mistake in this version of the plugin-  the ARR tool was removed for the release version but the tool button was not. You won't be able to use the QGIS 2 version in its place as there is slightly different API and dependencies.

If you email support@tuflow.com I will be happy to send you the latest developmental version of the plugin with a functional ARR tool for QGIS 3.
