### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'matplotlib'


### ISSUE THREAD

**Issue by zoran2k** [TUFLOW-Support/QGIS-TUFLOW-Plugin#24]
Couldn't load plugin 'tuflow' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\__init__.py", line 73, in classFactory
    from .tuflowqgis_menu import tuflowqgis_menu
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_menu.py", line 27, in <module>
    from .tuflowqgis_dialog import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_dialog.py", line 32, in <module>
    from .tuflowqgis_library import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_library.py", line 40, in <module>
    import matplotlib
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'matplotlib'

```
tuflow 3.1.2.3, QGIS 3.14.15-Pi on Windows 10

**Comment by TUFLOW-Support** [comment]
Are you installing QGIS using the standalone installer or OSGEO4W?

**Comment by zoran2k** [comment]
HI,

I have OSGeo4W 64 bit Installation.. and am unsing QGIS Pi 3.14.15

Best, Andreas


Von: TUFLOW Support
Gesendet: Mittwoch, 23. September 2020 01:07
An: TUFLOW-Support/QGIS-TUFLOW-Plugin
Cc: zoran2k; Author
Betreff: Re: [TUFLOW-Support/QGIS-TUFLOW-Plugin] Uncaught ModuleNotFoundError:No module named 'matplotlib' (#24)

Are you installing QGIS using the standalone installer or OSGEO4W?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by TUFLOW-Support** [comment]
HI Andreas, can you please double check you have installed the python3-matplotlib library through the advanced install
