### ISSUE TITLE
Python Error v3.1.7

### ISSUE THREAD

**Issue by ZedeN1** [TUFLOW-Support/QGIS-TUFLOW-Plugin#30]
<details>
  <summary>System Info Linux</summary>
  
  ```
QGIS version
3.18.3-Zürich
QGIS code revision
735cc85be9
Compiled against Qt
5.12.8
Running against Qt
5.12.8
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
Compiled against PDAL
2.0.1
Running against PDAL
2.0.1 (git-version: Release)
PostgreSQL Client Version
12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Ubuntu 20.04.2 LTS

```
  
</details>

<details>
  <summary>Python error Linux</summary>
  
```java
2021-06-17T12:33:46     WARNING    Traceback (most recent call last):
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_menu.py", line 478, in openResultsPlottingWindow
              self.resultsPlottingDock = TuView(self.iface, removeTuview=self.removeTuviewAction,
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_tuviewer/tuflowqgis_tuview.py", line 95, in __init__
              self.tuContextMenu.loadPlotMenu(0)
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_tuviewer/tuflowqgis_tumenucontext.py", line 81, in loadPlotMenu
              self.plotMenu.addAction(viewToolbar.axisFontSize_action)
             AttributeError: 'ViewToolbar' object has no attribute 'axisFontSize_action'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_menu.py", line 481, in openResultsPlottingWindow
              self.resultsPlottingDock = TuView(self.iface)
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_tuviewer/tuflowqgis_tuview.py", line 95, in __init__
              self.tuContextMenu.loadPlotMenu(0)
              File "/home/pavel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_tuviewer/tuflowqgis_tumenucontext.py", line 81, in loadPlotMenu
              self.plotMenu.addAction(viewToolbar.axisFontSize_action)
             AttributeError: 'ViewToolbar' object has no attribute 'axisFontSize_action'
```
 
</details>

<details>
  <summary>Python error Windows</summary>
  
```java
2021-06-17T14:39:42     WARNING    Traceback (most recent call last):
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_menu.py", line 479, in openResultsPlottingWindow
              reloadTuview=self.reloadTuviewAction)
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_tuviewer\tuflowqgis_tuview.py", line 95, in __init__
              self.tuContextMenu.loadPlotMenu(0)
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_tuviewer\tuflowqgis_tumenucontext.py", line 81, in loadPlotMenu
              self.plotMenu.addAction(viewToolbar.axisFontSize_action)
             AttributeError: 'ViewToolbar' object has no attribute 'axisFontSize_action'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_menu.py", line 481, in openResultsPlottingWindow
              self.resultsPlottingDock = TuView(self.iface)
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_tuviewer\tuflowqgis_tuview.py", line 95, in __init__
              self.tuContextMenu.loadPlotMenu(0)
              File "C:/Users/Pavel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow\tuflowqgis_tuviewer\tuflowqgis_tumenucontext.py", line 81, in loadPlotMenu
              self.plotMenu.addAction(viewToolbar.axisFontSize_action)
             AttributeError: 'ViewToolbar' object has no attribute 'axisFontSize_action'

```
 
</details>

**Comment by ZedeN1** [comment]
The error goes away after QGIS restart on Windows. Haven't checked on Linux

**Comment by TUFLOW-Support** [comment]
Thanks for checking. My guess is that TUFLOW Viewer isn't unloading properly when the plugin is upgrading. I'll have a closer look.
