### ISSUE TITLE
[Linux - v3.11 and v3.11.0.1] ImportError: cannot import name 'DETACHED_PROCESS' from 'subprocess' 

### ISSUE THREAD

**Issue by ZedeN1** [TUFLOW-Support/QGIS-TUFLOW-Plugin#39]
Updating to the newest available plugin in the QGIS repository v3.11 / developer plugin v3.11.0.1 breaks the plugin on Linux. 

```
Couldn't load plugin 'tuflow' due to an error when calling its classFactory() method 

ImportError: cannot import name 'DETACHED_PROCESS' from 'subprocess' (/usr/lib/python3.10/subprocess.py) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/__init__.py", line 78, in classFactory
    from .tuflowqgis_menu import tuflowqgis_menu
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tuflow/tuflowqgis_menu.py", line 44, in 
    from subprocess import Popen, PIPE, DETACHED_PROCESS
ImportError: cannot import name 'DETACHED_PROCESS' from 'subprocess' (/usr/lib/python3.10/subprocess.py)


Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527200 

Python Path:
/usr/share/qgis/python
/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python
/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python
/home/rhianna/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
```

```
uname -a
Linux inver 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

**Comment by ZedeN1** [comment]
Below works, but not sure if it is appropriate.

Changing ``

```
from subprocess import Popen, PIPE, DETACHED_PROCESS
import sys
```

to 

```
import sys
if sys.platform != 'win32':
    from subprocess import Popen, PIPE
else:
    from subprocess import Popen, PIPE, DETACHED_PROCESS
```

and changing

```
       process = subprocess.Popen(command, creationflags=DETACHED_PROCESS, start_new_session=True)
```
to 

```
        if sys.platform != 'win32':
            process = subprocess.Popen(command, cwd="/",
                 stdout=subprocess.PIPE,
                 stderr=subprocess.STDOUT,
                 start_new_session=True)
        else:
            process = subprocess.Popen(command, creationflags=DETACHED_PROCESS, start_new_session=True)
```

**Comment by ZedeN1** [comment]
v3.11.1 fixed the issue.
